config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/about',                to: 'static_pages#about'
  get '/help',                 to: 'static_pages#help'
  get '/contact',              to: 'static_pages#contact'
  get '/terms-and-conditions', to: 'static_pages#terms', as: 'terms'
  get '/signup',               to: 'users#new'
  resources :users, except: [:index]
  get '/login',                to: 'sessions#new'
  post '/login',               to: 'sessions#create'
  delete 'logout',             to: 'sessions#destroy'
  resources :restaurants do
    resources :reviews, except: [:index, :show]
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :restaurants
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :category
  has_many :reviews, dependent: :destroy

  before_validation { self.name = name.titleize }
  before_validation { self.city = city.titleize }
  before_validation { self.county = county.titleize }

  validates :name, presence: true, uniqueness: { scope: [:category_id, :city, :county],
                                   message: " error: restaurant already exists" }
  validates :city, presence: true
  validates :county, presence: true

  def Restaurant.search(params)
    restaurants = Restaurant.where(category_id: params[:category].to_i)
    restaurants = restaurants.where("name like ?", "%#{params[:search].titleize}%") if params[:search].present?
    restaurants = restaurants.where("city like ? or county like ?", "%#{params[:location].titleize}%",
                                    "%#{params[:location].titleize}%") if params[:location].present?
    restaurants
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant

  default_scope -> { order(created_at: :desc) }

  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 1000 }
  validates :rating, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = URI::MailTo::EMAIL_REGEXP

  has_many :reviews, dependent: :destroy

  before_save { email.downcase! }

  validates :name,  presence: true, length: { maximum: 40 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 8 }, allow_nil: true

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper

  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please login to continue"
      redirect_to login_url
    end
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:new, :edit, :create, :update, :destroy]
  before_action :admin_user, only: [:edit, :update, :destroy]

  def new
    @restaurant = Restaurant.new
  end

  def show
    @reviews = Review.where(restaurant_id: @restaurant)
    @paginated_reviews = @reviews.paginate(page: params[:page])
    if @reviews.blank?
      @avg_rating = 0
    else
      @avg_rating = @reviews.average(:rating).round(2)
    end
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @restaurant.update_attributes(restaurant_params)
      flash[:success] = "Restaurant successfully updated"
      redirect_to @restaurant
    else
      render 'edit'
    end
  end

  def destroy
    @restaurant.destroy
    flash[:success] = "Restaurant successfully deleted"
    redirect_to root_url
  end

  def search
    @restaurants = Restaurant.search(params).paginate(page: params[:page])
  end

  private
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    def restaurant_params
      params.require(:restaurant).permit(:name, :description, :category_id, :address_1, :address_2,
                                         :city, :county, :phone, :email)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: [:new, :create]
  before_action :logged_in_user, only: [:new, :create]

  def new
    @review = Review.new(restaurant: @restaurant)
  end

  def create
    @review = current_user.reviews.build(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to @restaurant
    else
      render 'new'
    end
  end

  private

    def set_restaurant
      @restaurant = Restaurant.find(params[:restaurant_id])
    end

    def review_params
      params.require(:review).permit(:content, :rating)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in(user)
      redirect_back_or user
    else
      flash.now[:danger] = "Invalid email/password"
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def help
  end

  def contact
  end

  def terms
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @reviews = @user.reviews.paginate(page: params[:page])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "You have successfully signed up!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile successfully updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User successfully deleted"
    redirect_to root_url
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to root_url unless current_user?(@user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(title = "")
    base_title = "Restaurant Rater"
    title.empty? ? base_title : "#{base_title} | #{title}"
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    current_user = nil
  end

  def current_user?(user)
    user == current_user
  end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Restaurant Rater 2022
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "Terms & Conditions", terms_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Restaurant Rater", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",  root_path %></li>
        <li><%= link_to "Help",  help_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              My Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Logout", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Login", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <script>
      $('.star-rating').raty({
        path: '/assets/',
        readOnly: true,
        score: function() {
          return $(this).attr('data-score');
        }
      });
    </script>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/restaurants/_restaurant_info_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@restaurant) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :description %>
      <%= f.text_area :description %>

      <%= f.label :category %>
      <%= f.select :category_id, Category.all.map { |f| [f.name, f.id] } %>

      <%= f.label :address_1 %>
      <%= f.text_field :address_1 %>

      <%= f.label :address_2 %>
      <%= f.text_field :address_2 %>

      <%= f.label :city %>
      <%= f.text_field :city %>

      <%= f.label :county %>
      <%= f.text_field :county %>

      <%= f.label :phone %>
      <%= f.text_field :phone %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.submit yield(:button_text), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/restaurants/edit.html.erb
<% provide(:title, 'Edit restaurant') %>
<% provide(:button_text, 'Save changes') %>

<div class="center">
  <h1>Edit restaurant</h1>
</div>

<%= render 'restaurant_info_form' %>

app/views/restaurants/new.html.erb
<% provide(:title, 'Add a restaurant') %>
<% provide(:button_text, 'Add restaurant') %>

<div class="center">
  <h1>Add a restaurant</h1>
</div>

<%= render 'restaurant_info_form' %>

app/views/restaurants/search.html.erb
<% provide(:title, "Search results") %>

<div>
  <h3> <%= @restaurants.count %> restaurants match your search criteria ....</h3>
  <p>Can't find what you're looking for? <%= link_to "Add a restaurant", new_restaurant_path %></p>
</div>
<div>
  <% @restaurants.each do |restaurant| %>
    <p><%= link_to restaurant.name, restaurant, class: "btn btn-lg" %></p>
  <% end %>
  <%= will_paginate @restaurants %>
</div>

app/views/restaurants/show.html.erb
<% provide(:title, @restaurant.name) %>
<div>
  <h1><%= @restaurant.name %>
    <span class="star-rating" data-score=<%= @avg_rating %> ></span>
    <% if current_user.try(:admin?) %>
     <%= link_to "Edit Restaurant", edit_restaurant_path(@restaurant), class: 'btn btn-primary' %>
     <%= link_to "Delete Restaurant", @restaurant, method: :delete, data: { confirm: "You sure?" },
                                                   class: 'btn btn-danger' %>
    <% end %>
  </h1>

  <p><strong>Description:</strong> <%= @restaurant.description %></p>

  <p><strong>Category:</strong> <%= @restaurant.category.name %></p>

  <p><strong>Address:</strong> <%= [@restaurant.address_1, @restaurant.address_2, @restaurant.city,
                                    @restaurant.county].reject(&:blank?).join(", ") %></p>

  <p><strong>Phone:</strong> <%= @restaurant.phone %></p>

  <p><strong>Email:</strong> <%= @restaurant.email %></p>
</div>
<div>
  <h2>Reviews (<%= @restaurant.reviews.count %>)
  <%= link_to "Write a review", new_restaurant_review_path(@restaurant), class: "btn btn-primary" %></h2>
  <div class="reviews">
    <% @paginated_reviews.each do |review| %>
      <li>
        <span class="star-rating" data-score=<%= review.rating %> ></span>
        <p> <%= review.content %> </p>
        <span class="timestamp">
          Posted on <%= review.created_at.strftime("%d/%m/%Y") %>
          by <%= link_to review.user.name, review.user %>
        </span>
      </li>
    <% end %>
    <%= will_paginate @paginated_reviews %>
  </div>
</div>

app/views/reviews/_review.html.erb
<li>
  <%= link_to review.restaurant.name, review.restaurant %>
  <span class="star-rating" data-score=<%= review.rating %> ></span>
  <p> <%= review.content %> </p>
  <span class="timestamp">
    Posted on <%= review.created_at.strftime("%d/%m/%Y") %>
  </span>
</li>

app/views/reviews/new.html.erb
<% provide(:title, 'Add a review') %>
<div class="center">
  <h1>Add a review for <%= @restaurant.name %></h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [@restaurant, @review] do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.text_area :content, placeholder: "Compose your review..." %>

      <%= f.label :rating, "Rating 1 - 5" %>
      <%= f.number_field :rating, value: 1, min: 1, max: 5 %>

      <%= f.submit "Submit your review", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
<script>
$('#star-rating').raty({
    path: '/assets',
    scoreName: 'review[rating]'
});
</script>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_search_form.html.erb
<p>Find a restaurant</p>
  <%= form_tag search_restaurants_path, method: :get do |f| %>
    <%= text_field_tag :search, nil, placeholder: "Search by restaurant's name" %>
    <%= text_field_tag :location, nil, placeholder: "Search by city or county" %>
    <%= select_tag :category, options_for_select(Category.all.map{ |c| [c.name, c.id] } ) %>
    <%= submit_tag "Search", class: "btn btn-primary" %>
  <% end %>
<p> New restaurant to review? <%= link_to "Add a restaurant!", new_restaurant_path %></p>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<div class="center jumbotron">
  <h1>About</h1>
  <h2>Restaurant Rater is a simple and easy app to help you decide where you want to eat!<h2>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>

<div class="center jumbotron">
  <h1>Contact</h1>
  <h2>Please email us at <a href="#">help@restaurant-rater.co.uk</a></h2>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>

<div class="center jumbotron">
  <h1>Help</h1>
  <h2>Please email us at <a href="#">help@restaurant-rater.co.uk</a> should you require any assistance.</h2>
</div>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to Restaurant Rater</h1>
  <% unless logged_in? %>
    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
    <%= link_to "Write a review!", new_restaurant_path, class: "btn btn-lg btn-primary" %>
  <% end %>
</div>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'shared/search_form' %>
  </div>
</div>

app/views/static_pages/terms.html.erb
<% provide(:title, "Terms and Conditions") %>

<div class="center jumbotron">
  <h1>Terms & Conditions</h1>
  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt
  ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
  laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in
  voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat
  non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</div>

app/views/users/_user_info_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit yield(:button_text), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<% provide(:title, 'Edit profile') %>
<% provide(:button_text, 'Save changes') %>

<div class="center">
  <h1>Edit profile</h1>
</div>

<%= render 'user_info_form' %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>

<div class="center">
  <h1>Sign up</h1>
</div>

<%= render 'user_info_form' %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<h1><%= @user.name %>
  <% if current_user.try(:admin?) && !current_user?(@user) %>
   <%= link_to "Delete User", @user, method: :delete, data: { confirm: "You sure?" },
                                     class: 'btn btn-danger' %>
  <% end %>
</h1>
<% if current_user?(@user) %>
  <aside class="col-md-4">
    <h3>Post a new review </h3>
    <%= render 'shared/search_form' %>
  </aside>
<% end %>
<div class="col-md-8">
  <% if @user.reviews.any? %>
    <h3>Previous reviews (<%= @user.reviews.count %>)</h3>
    <ol class="reviews">
      <%= render @reviews %>
    </ol>
    <%= will_paginate @reviews %>
  <% end %>
</div>